import { Router } from 'express';
import { supabase } from '../supabase.js';
import { openai, isAIEnabled, DEAL_ANALYSIS_SYSTEM_PROMPT, generateDealContext } from '../openai.js';
import { z } from 'zod';

const router = Router();

// Validation schemas
const chatMessageSchema = z.object({
  message: z.string().min(1),
  history: z.array(z.object({
    role: z.enum(['user', 'assistant']),
    content: z.string(),
  })).optional(),
});

// POST /api/deals/:dealId/chat - Chat with AI about a deal
router.post('/deals/:dealId/chat', async (req, res) => {
  try {
    if (!isAIEnabled()) {
      return res.status(503).json({
        error: 'AI service unavailable',
        message: 'OpenAI API key not configured',
      });
    }

    const { dealId } = req.params;
    const { message, history = [] } = chatMessageSchema.parse(req.body);

    // Fetch deal data for context
    const { data: deal, error: dealError } = await supabase
      .from('Deal')
      .select(`
        *,
        company:Company(*),
        documents:Document(*),
        activities:Activity(*)
      `)
      .eq('id', dealId)
      .single();

    if (dealError || !deal) {
      return res.status(404).json({ error: 'Deal not found' });
    }

    // Build messages array
    const messages: any[] = [
      { role: 'system', content: DEAL_ANALYSIS_SYSTEM_PROMPT },
      { role: 'system', content: `Current Deal Context:\n${generateDealContext(deal)}` },
    ];

    // Add conversation history
    history.forEach((msg: any) => {
      messages.push({ role: msg.role, content: msg.content });
    });

    // Add current message
    messages.push({ role: 'user', content: message });

    // Call OpenAI
    const completion = await openai!.chat.completions.create({
      model: 'gpt-4-turbo-preview',
      messages,
      temperature: 0.7,
      max_tokens: 1000,
    });

    const response = completion.choices[0]?.message?.content || 'No response generated.';

    // Log activity
    await supabase.from('Activity').insert({
      dealId,
      type: 'NOTE_ADDED',
      title: 'AI Chat Query',
      description: message.substring(0, 100) + (message.length > 100 ? '...' : ''),
      metadata: { type: 'ai_chat' },
    });

    res.json({
      response,
      model: 'gpt-4-turbo-preview',
      dealId,
    });
  } catch (error) {
    if (error instanceof z.ZodError) {
      return res.status(400).json({ error: 'Validation error', details: error.errors });
    }
    console.error('Error in AI chat:', error);
    res.status(500).json({ error: 'Failed to process AI chat' });
  }
});

// POST /api/deals/:dealId/generate-thesis - Generate AI investment thesis
router.post('/deals/:dealId/generate-thesis', async (req, res) => {
  try {
    if (!isAIEnabled()) {
      return res.status(503).json({
        error: 'AI service unavailable',
        message: 'OpenAI API key not configured',
      });
    }

    const { dealId } = req.params;

    // Fetch deal data
    const { data: deal, error: dealError } = await supabase
      .from('Deal')
      .select(`
        *,
        company:Company(*),
        documents:Document(*),
        activities:Activity(*)
      `)
      .eq('id', dealId)
      .single();

    if (dealError || !deal) {
      return res.status(404).json({ error: 'Deal not found' });
    }

    const prompt = `Based on the following deal information, generate a concise investment thesis (2-3 sentences) that highlights the key opportunity and any notable risks or considerations.

Deal Information:
${generateDealContext(deal)}

Generate a professional investment thesis that a PE analyst would write. Be specific about the opportunity and any flags that need attention.`;

    const completion = await openai!.chat.completions.create({
      model: 'gpt-4-turbo-preview',
      messages: [
        { role: 'system', content: DEAL_ANALYSIS_SYSTEM_PROMPT },
        { role: 'user', content: prompt },
      ],
      temperature: 0.7,
      max_tokens: 300,
    });

    const thesis = completion.choices[0]?.message?.content || 'Unable to generate thesis.';

    // Update deal with new thesis
    const { error: updateError } = await supabase
      .from('Deal')
      .update({ aiThesis: thesis })
      .eq('id', dealId);

    if (updateError) {
      console.error('Error updating thesis:', updateError);
    }

    // Log activity
    await supabase.from('Activity').insert({
      dealId,
      type: 'STATUS_UPDATED',
      title: 'AI Thesis Generated',
      description: 'Investment thesis automatically generated by AI',
      metadata: { type: 'thesis_generation' },
    });

    res.json({
      thesis,
      dealId,
      updated: !updateError,
    });
  } catch (error) {
    console.error('Error generating thesis:', error);
    res.status(500).json({ error: 'Failed to generate thesis' });
  }
});

// POST /api/deals/:dealId/analyze-risks - Analyze deal risks
router.post('/deals/:dealId/analyze-risks', async (req, res) => {
  try {
    if (!isAIEnabled()) {
      return res.status(503).json({
        error: 'AI service unavailable',
        message: 'OpenAI API key not configured',
      });
    }

    const { dealId } = req.params;

    // Fetch deal data
    const { data: deal, error: dealError } = await supabase
      .from('Deal')
      .select(`
        *,
        company:Company(*),
        documents:Document(*),
        activities:Activity(*)
      `)
      .eq('id', dealId)
      .single();

    if (dealError || !deal) {
      return res.status(404).json({ error: 'Deal not found' });
    }

    const prompt = `Analyze the following deal and identify the top 3-5 key risks that an investor should consider. For each risk, provide a severity level (High/Medium/Low) and a brief mitigation suggestion.

Deal Information:
${generateDealContext(deal)}

Format your response as a JSON array of risk objects with fields: title, description, severity, mitigation`;

    const completion = await openai!.chat.completions.create({
      model: 'gpt-4-turbo-preview',
      messages: [
        { role: 'system', content: DEAL_ANALYSIS_SYSTEM_PROMPT },
        { role: 'user', content: prompt },
      ],
      temperature: 0.7,
      max_tokens: 800,
      response_format: { type: 'json_object' },
    });

    let risks;
    try {
      const content = completion.choices[0]?.message?.content || '{"risks":[]}';
      const parsed = JSON.parse(content);
      risks = parsed.risks || parsed;
    } catch {
      risks = [{ title: 'Analysis Error', description: 'Could not parse risk analysis', severity: 'Medium' }];
    }

    res.json({
      risks,
      dealId,
    });
  } catch (error) {
    console.error('Error analyzing risks:', error);
    res.status(500).json({ error: 'Failed to analyze risks' });
  }
});

// GET /api/ai/status - Check AI service status
router.get('/ai/status', (req, res) => {
  res.json({
    enabled: isAIEnabled(),
    model: 'gpt-4-turbo-preview',
  });
});

export default router;
