// VDR Report generator extracted from page.tsx so the page itself stays
// under the 500-line cap. Builds the same markdown text as the inline
// implementation and triggers a browser download via Blob.
// Behavior is unchanged — same filename pattern, same content, same
// download trigger.

import type { Folder, FolderInsights, VDRFile } from "@/lib/vdr/types";

interface GenerateReportArgs {
  activeFolder: Folder;
  activeFolderInsights: FolderInsights | null | undefined;
  filteredFiles: VDRFile[];
}

export function generateVDRReport({ activeFolder, activeFolderInsights, filteredFiles }: GenerateReportArgs) {
  const folderInsights = activeFolderInsights;

  const report = `# VDR Analysis Report - ${activeFolder.name}
Generated: ${new Date().toLocaleString()}

## Summary
${folderInsights?.summary || "No summary available."}

**Completion Status:** ${folderInsights?.completionPercent || 0}%
**Total Files:** ${activeFolder.fileCount}

## Red Flags (${folderInsights?.redFlags?.length || 0})
${(folderInsights?.redFlags || [])
  .map(
    (flag) => `
### ${flag.title} [${flag.severity.toUpperCase()}]
${flag.description}
`,
  )
  .join("\n")}

## Missing Documents (${folderInsights?.missingDocuments?.length || 0})
${(folderInsights?.missingDocuments || []).map((doc) => `- ${doc.name}`).join("\n")}

## Files in Folder
${filteredFiles
  .map(
    (file) => `
- **${file.name}** (${file.size})
  - Analysis: ${file.analysis.label}
  - ${file.analysis.description}
  - Author: ${file.author.name}
  - Date: ${file.date}
`,
  )
  .join("\n")}

---
Generated by PE OS VDR System
`;

  const blob = new Blob([report], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `VDR_Report_${activeFolder.name.replace(/\s+/g, "_")}_${Date.now()}.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
